#!/usr/bin/env python3
"""Full-corpus INVENTORY table — every recorded set × what data + what results we have.

One row per set in `dataset/sets.csv`, joining:
  * GT      — Vitruve / Stance per-rep count (the reference truth)
  * SB      — SmartBarbell per-rep count
  * video   — R2 (manifest) / git (local) / —
  * watch   — does a `<set_id>_watch.csv` exist
  * CV auto — seed-free AUTO rep count (the blind number); CV adj — tap/seed path
  * watch auto — PoC detector (rep_detect+gate_reps); watch adj — wave segmenter

watch columns are computed LIVE; CV-auto is read from the latest board run if cached
(seed-free is slow, so we don't re-run it here). Writes a markdown table to
docs/corpus-inventory.md. This is the antidote to the "analyzed a subset" blind spot
(learning #30) — it shows, at a glance, every set and every gap.

    python analysis/scripts/inventory.py
"""
from __future__ import annotations
import csv
import glob
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.dirname(__file__))
import cv_eval  # noqa: E402

REPO = cv_eval.REPO
RAW = os.path.join(REPO, "dataset", "raw")


def _counts_by_vendor():
    out = {}
    for r in csv.DictReader(open(os.path.join(REPO, "dataset", "rep_metrics.csv"))):
        if (r.get("rep_index") or "").strip() and (r.get("flag") or "") != "phantom" \
                and r.get("metric") == "mean_velocity":
            out.setdefault((r["set_id"], r["vendor"]), 0)
            out[(r["set_id"], r["vendor"])] += 1
    return out


def _manifest_sids():
    out = {}
    p = os.path.join(RAW, "manifest.csv")
    if os.path.exists(p):
        for r in csv.DictReader(open(p)):
            out[r["set_id"]] = r.get("resolution", "")
    return out


def _cv_auto_from_logs():
    """Parse the most recent seed-free board logs for AUTO counts (count only)."""
    out = {}
    for fn in ["/tmp/strict_full.log", "/tmp/r2_check.log", "/tmp/newclips.log",
               "/tmp/recall_full.log"]:
        if not os.path.exists(fn):
            continue
        for l in open(fn):
            l = re.sub(r"\x1b\[[0-9;]*m", "", l)
            m = re.match(r"\s*(\d{8}-\w+-\d+)\s+\w+\s+\d+\s+(\d+)\(", l)
            if m:
                out[m.group(1)] = int(m.group(2))
    return out


def _watch_counts(sid):
    """(auto = PoC detector, adj = wave segmenter) for a watch session, or (None, None)."""
    p = os.path.join(RAW, f"{sid}_watch.csv")
    if not os.path.exists(p):
        return None, None
    try:
        from vbt_analysis.ingest import load_session
        from vbt_analysis.velocity import vertical_acceleration, integrate_with_zupt, rep_metrics, gate_reps
        from vbt_analysis.rep_detect import detect_turnarounds
        from vbt_analysis import wave_segment as ws
        import numpy as np
        df = load_session(p); t = df["t"].to_numpy(float); a = vertical_acceleration(df)
        anchors = detect_turnarounds(t, a)
        auto = len(gate_reps(rep_metrics(t, integrate_with_zupt(t, a, anchors), anchors)))
        adj = ws.segment(t, a).count
        return auto, adj
    except Exception:
        return None, None


def main():
    cnt = _counts_by_vendor()
    manifest = _manifest_sids()
    cv_auto = _cv_auto_from_logs()
    local_video = {sid for sid, v in cv_eval.CLIPS.items()
                   if os.path.exists(os.path.join(REPO, v[0]))}

    rows = list(csv.DictReader(open(os.path.join(REPO, "dataset", "sets.csv"))))
    rows.sort(key=lambda r: (r["date"], r["lift"], r.get("set_index", "")))

    hdr = ("| date | lift | set | reps | GT (vit/stance) | video | SB | CV auto | CV adj "
           "| watch auto | watch adj |")
    sep = "|" + "---|" * 11
    out = ["# Corpus inventory (auto-generated by scripts/inventory.py)", "",
           "One row per recorded set. `—` = none/not applicable; `?` = video exists but not "
           "yet CV-scored (e.g. 4K pending proxy). CV auto = seed-free blind; CV adj = tap/seed "
           "path. watch auto = PoC detector; watch adj = wave segmenter. Regenerate after any "
           "upload; pair with `scripts/coverage.py`.", "", hdr, sep]
    n_gt = n_vid = n_watch = 0
    for r in rows:
        sid = r["set_id"]
        vit = cnt.get((sid, "vitruve")); stance = cnt.get((sid, "stance"))
        sb = cnt.get((sid, "smartbarbell"))
        gt = f"vit {vit}" if vit else (f"stance {stance}" if stance else "—")
        if vit or stance:
            n_gt += 1
        if sid in manifest:
            vid = "R2"; n_vid += 1
        elif sid in local_video:
            vid = "git"; n_vid += 1
        else:
            vid = "—"
        # CV auto: cached count; if a video exists but no cached score → '?'
        ca = cv_auto.get(sid)
        cv_a = str(ca) if ca is not None else ("?" if vid != "—" else "—")
        cv_adj = "—"   # tap path not systematically cached; see cv_eval.CLIPS notes
        wa, wadj = _watch_counts(sid)
        if wa is not None:
            n_watch += 1
        actual = r.get("actual_reps") or "?"
        out.append(f"| {r['date']} | {r['lift']} | {r.get('set_index','')} | {actual} "
                   f"| {gt} | {vid} | {sb if sb else '—'} | {cv_a} | {cv_adj} "
                   f"| {wa if wa is not None else '—'} | {wadj if wadj is not None else '—'} |")
    out += ["", f"**{len(rows)} sets · {n_gt} with Vitruve/Stance GT · {n_vid} with video "
            f"· {n_watch} with watch.** GT-but-no-video/watch sets and CV/watch board gaps: "
            f"run `scripts/coverage.py`."]
    doc = os.path.join(REPO, "docs", "corpus-inventory.md")
    open(doc, "w").write("\n".join(out) + "\n")
    print("\n".join(out))
    print(f"\nwrote {doc}")


if __name__ == "__main__":
    main()
